export const POLICY_REGISTRY_FALLBACK_ABI: string[] = [
  "function registerPolicy(bytes32 policyId, uint256 version, uint256 destinationChainId, address executor, uint256 activation, uint256 expiry, tuple(bytes32 actionId, address target, bytes4 selector, bytes params, uint256 nativeValue, uint256 earliestExecution, uint256 expiry)[] actions) external",
  "event PolicyApproved(bytes32 indexed policyId, uint256 version, address indexed safe, uint256 destinationChainId, address executor, uint256 activation, uint256 expiry, bytes encodedActions)",
];

export const SAFE_ROOT_POLICY_EXECUTOR_FALLBACK_ABI: string[] = [
  "function activatePolicy(bytes attestcoinProof, bytes32 policyId, uint256 version, address safe, uint256 destinationChainId, address executor, uint256 activation, uint256 expiry, tuple(bytes32 actionId, address target, bytes4 selector, bytes params, uint256 nativeValue, uint256 earliestExecution, uint256 expiry)[] actions) external",
  "function executeAction(bytes32 policyId, bytes32 actionId, address target, bytes4 selector, bytes params, uint256 nativeValue) external payable",
  "function guardianPause(bytes32 policyId, string reason) external",
  "function getPolicy(bytes32 policyId) view returns (tuple(bytes32 policyId, uint256 version, address safe, uint256 activation, uint256 expiry, bool active, bool paused))",
  "function getAction(bytes32 policyId, bytes32 actionId) view returns (tuple(bytes32 actionId, address target, bytes4 selector, bytes params, uint256 nativeValue, uint256 earliestExecution, uint256 expiry, bool executed))",
  "event PolicyActivated(bytes32 indexed policyId, uint256 version, address safe, uint256 activation, uint256 expiry)",
  "event ActionExecuted(bytes32 indexed policyId, bytes32 indexed actionId, address target, bool success)",
  "event GuardianPaused(bytes32 indexed policyId, address guardian, string reason, uint256 timestamp)",
  "error PolicyNotActive()",
  "error PolicyExpired()",
  "error ExecutorPaused()",
  "error ActionNotFound()",
  "error ActionAlreadyExecuted()",
  "error TargetMismatch()",
  "error FunctionNotAllowed()",
  "error CalldataMismatch()",
  "error AmountExceedsApproval()",
  "error NotYetEligible()",
  "error ActionExpired()",
  "error UnsupportedSourceChain()",
  "error SourceTransactionFailed()",
  "error EmitterNotApproved()",
  "error SafeMismatch()",
  "error WrongDestinationChain()",
  "error WrongExecutor()",
  "error StalePolicyVersion()",
  "error PolicyNotYetValid()",
  "error PolicyAlreadyExpired()",
  "error ProofAlreadyUsed()",
];
