export const actionInputComponents = [
  { name: "actionId", type: "bytes32" },
  { name: "target", type: "address" },
  { name: "selector", type: "bytes4" },
  { name: "params", type: "bytes" },
  { name: "nativeValue", type: "uint256" },
  { name: "earliestExecution", type: "uint256" },
  { name: "expiry", type: "uint256" },
] as const;

export const policyRegistryAbi = [
  {
    type: "function",
    name: "registerPolicy",
    stateMutability: "nonpayable",
    inputs: [
      { name: "policyId", type: "bytes32" },
      { name: "version", type: "uint256" },
      { name: "destinationChainId", type: "uint256" },
      { name: "executor", type: "address" },
      { name: "activation", type: "uint256" },
      { name: "expiry", type: "uint256" },
      { name: "actions", type: "tuple[]", components: actionInputComponents },
    ],
    outputs: [],
  },
  {
    type: "event",
    name: "PolicyApproved",
    inputs: [
      { name: "policyId", type: "bytes32", indexed: true },
      { name: "version", type: "uint256", indexed: false },
      { name: "safe", type: "address", indexed: true },
      { name: "destinationChainId", type: "uint256", indexed: false },
      { name: "executor", type: "address", indexed: false },
      { name: "activation", type: "uint256", indexed: false },
      { name: "expiry", type: "uint256", indexed: false },
      { name: "encodedActions", type: "bytes", indexed: false },
    ],
    anonymous: false,
  },
] as const;

export const safeRootPolicyExecutorAbi = [
  {
    type: "function",
    name: "activatePolicy",
    stateMutability: "nonpayable",
    inputs: [
      { name: "attestcoinProof", type: "bytes" },
      { name: "policyId", type: "bytes32" },
      { name: "version", type: "uint256" },
      { name: "safe", type: "address" },
      { name: "destinationChainId", type: "uint256" },
      { name: "executor", type: "address" },
      { name: "activation", type: "uint256" },
      { name: "expiry", type: "uint256" },
      { name: "actions", type: "tuple[]", components: actionInputComponents },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "executeAction",
    stateMutability: "payable",
    inputs: [
      { name: "policyId", type: "bytes32" },
      { name: "actionId", type: "bytes32" },
      { name: "target", type: "address" },
      { name: "selector", type: "bytes4" },
      { name: "params", type: "bytes" },
      { name: "nativeValue", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "guardianPause",
    stateMutability: "nonpayable",
    inputs: [
      { name: "policyId", type: "bytes32" },
      { name: "reason", type: "string" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "getPolicy",
    stateMutability: "view",
    inputs: [{ name: "policyId", type: "bytes32" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "policyId", type: "bytes32" },
          { name: "version", type: "uint256" },
          { name: "safe", type: "address" },
          { name: "activation", type: "uint256" },
          { name: "expiry", type: "uint256" },
          { name: "paused", type: "bool" },
          { name: "exists", type: "bool" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "getAction",
    stateMutability: "view",
    inputs: [
      { name: "policyId", type: "bytes32" },
      { name: "actionId", type: "bytes32" },
    ],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          ...actionInputComponents,
          { name: "executed", type: "bool" },
        ],
      },
    ],
  },
  {
    type: "event",
    name: "PolicyActivated",
    inputs: [
      { name: "policyId", type: "bytes32", indexed: true },
      { name: "version", type: "uint256", indexed: false },
      { name: "safe", type: "address", indexed: false },
      { name: "activation", type: "uint256", indexed: false },
      { name: "expiry", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ActionExecuted",
    inputs: [
      { name: "policyId", type: "bytes32", indexed: true },
      { name: "actionId", type: "bytes32", indexed: true },
      { name: "target", type: "address", indexed: false },
      { name: "success", type: "bool", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "GuardianPaused",
    inputs: [
      { name: "policyId", type: "bytes32", indexed: true },
      { name: "guardian", type: "address", indexed: false },
      { name: "reason", type: "string", indexed: false },
      { name: "timestamp", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  { type: "error", name: "PolicyNotActive", inputs: [] },
  { type: "error", name: "PolicyExpired", inputs: [] },
  { type: "error", name: "ExecutorPaused", inputs: [] },
  { type: "error", name: "ActionNotFound", inputs: [] },
  { type: "error", name: "ActionAlreadyExecuted", inputs: [] },
  { type: "error", name: "TargetMismatch", inputs: [] },
  { type: "error", name: "FunctionNotAllowed", inputs: [] },
  { type: "error", name: "CalldataMismatch", inputs: [] },
  { type: "error", name: "AmountExceedsApproval", inputs: [] },
  { type: "error", name: "NotYetEligible", inputs: [] },
  { type: "error", name: "ActionExpired", inputs: [] },
  { type: "error", name: "UnsupportedSourceChain", inputs: [] },
  { type: "error", name: "SourceTransactionFailed", inputs: [] },
  { type: "error", name: "EmitterNotApproved", inputs: [] },
  { type: "error", name: "SafeMismatch", inputs: [] },
  { type: "error", name: "WrongDestinationChain", inputs: [] },
  { type: "error", name: "WrongExecutor", inputs: [] },
  { type: "error", name: "StalePolicyVersion", inputs: [] },
  { type: "error", name: "PolicyNotYetValid", inputs: [] },
  { type: "error", name: "PolicyAlreadyExpired", inputs: [] },
  { type: "error", name: "ProofAlreadyUsed", inputs: [] },
] as const;

export const contractErrorToRejectionReason: Record<string, string> = {
  PolicyNotActive: "PolicyNotActive",
  PolicyExpired: "PolicyExpired",
  ExecutorPaused: "ExecutorPaused",
  TargetMismatch: "WrongTarget",
  FunctionNotAllowed: "FunctionNotAllowed",
  CalldataMismatch: "CalldataMismatch",
  AmountExceedsApproval: "AmountExceedsApproval",
  ActionAlreadyExecuted: "ActionAlreadyExecuted",
  WrongDestinationChain: "WrongDestinationChain",
  WrongExecutor: "WrongExecutor",
  StalePolicyVersion: "StalePolicyVersion",
  ProofAlreadyUsed: "ProofAlreadyUsed",
};
